/**
 * @author Petr Mrázek (xmraze03@stud.fit.vutbr.cz)
 */
package org.dethware.xmpp.client;

import java.awt.Color;
import java.util.TreeMap;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class ConversationFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConversationFrame
     */
    public ConversationFrame() {
        initComponents();
        conversationTabs.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                JTabbedPane pane = (JTabbedPane)e.getSource();
                // Get current tab
                int sel = pane.getSelectedIndex();
                if(sel != -1)
                {
                    String title = pane.getTitleAt(sel);
                    setTitle(title);
                    JLabel lab = (JLabel) conversationTabs.getTabComponentAt(sel);
                    if(lab != null)
                        lab.setOpaque(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conversationTabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conversationTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conversationTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane conversationTabs;
    // End of variables declaration//GEN-END:variables

    void openConversation(Conversation conversation, boolean only_if_new) {
        ConversationPanel panel = panelMap.get(conversation);
        if(panel == null)
        {
            int index = conversationTabs.getTabCount();
            panel = new ConversationPanel(conversation,index);
            Contact c = conversation.getContact();
            conversationTabs.insertTab( c.getName(), null, panel, null, index );
            conversationTabs.setSelectedIndex(index);
            JLabel title = new JLabel(conversationTabs.getTitleAt(index));
            conversationTabs.setTabComponentAt(index, title);
            panelMap.put(conversation, panel);
        }
        else if(!only_if_new)
        {
            int index = panel.getIndex();
            conversationTabs.setSelectedIndex(index);
        }
        else
        {
            int index = panel.getIndex();
            if(conversationTabs.getSelectedIndex() != index)
            {
                JLabel lab = (JLabel) conversationTabs.getTabComponentAt(index);
                lab.setBackground(Color.green);
                lab.setOpaque(true);
            }
        }
    }
    private TreeMap <Conversation,ConversationPanel> panelMap = new TreeMap<>();
}
